version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  node-express-docker:
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
    container_name: node-express-docker
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
  
volumes:
  node-express-docker:
  mongodb: